#!/bin/bash
# Quick reference for deploying the agent authentication fix

echo "======================================================================="
echo "🚀 DEPLOYMENT GUIDE: Agent Authentication Fix"
echo "======================================================================="
echo ""
echo "Changes made to Django backend:"
echo "  ✅ Added agent.resolvemeq.net to CSRF_TRUSTED_ORIGINS"
echo "  ✅ Created AgentAPIKeyAuthentication in base/authentication.py"
echo "  ✅ Created IsAuthenticatedOrAgent permission"
echo "  ✅ Updated update_ticket_status endpoint to accept agent auth"
echo "  ✅ Added AGENT_API_KEY configuration"
echo ""
echo "======================================================================="
echo "📋 DEPLOYMENT STEPS"
echo "======================================================================="
echo ""
echo "1. Deploy Django changes to production:"
echo "   git add ."
echo "   git commit -m 'Add agent API key authentication'"
echo "   git push"
echo ""
echo "2. Set environment variable on production Django server:"
echo "   export AGENT_API_KEY='resolvemeq-agent-secret-key-2026'"
echo "   # Or add to your .env file"
echo ""
echo "3. Configure Agent to send API key header:"
echo "   The agent needs to send this header with Django API requests:"
echo "   X-Agent-API-Key: resolvemeq-agent-secret-key-2026"
echo ""
echo "   Example (in agent's HTTP client):"
echo "   headers = {"
echo "       'Content-Type': 'application/json',"
echo "       'X-Agent-API-Key': 'resolvemeq-agent-secret-key-2026'"
echo "   }"
echo ""
echo "4. Set environment variable on agent server:"
echo "   export DJANGO_API_KEY='resolvemeq-agent-secret-key-2026'"
echo ""
echo "5. Test the complete flow:"
echo "   curl -X POST 'https://agent.resolvemeq.net/tickets/analyze/' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"ticket_id\": 1, ...}'"
echo ""
echo "======================================================================="
echo "🔑 API KEY DETAILS"
echo "======================================================================="
echo "Default API Key: resolvemeq-agent-secret-key-2026"
echo ""
echo "For production, consider using a stronger key:"
echo "  python3 -c \"import secrets; print(secrets.token_urlsafe(32))\""
echo ""
echo "Update in both places:"
echo "  - Django: AGENT_API_KEY environment variable"
echo "  - Agent: DJANGO_API_KEY environment variable"
echo ""
echo "======================================================================="
echo "✅ VERIFICATION"
echo "======================================================================="
echo "After deployment, verify with:"
echo "  python3 test_agent_auth.py"
echo "  python3 test_full_communication.py"
echo ""
echo "Expected: Agent can successfully update ticket status in Django"
echo "======================================================================="
