# Generated by Django 5.2.2 on 2026-04-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_kbmention'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kbmention',
            new_name='knowledge_b_target__cf07b0_idx',
            old_name='knowledge_ba_target__7f1c2e_idx',
        ),
        migrations.RenameIndex(
            model_name='kbmention',
            new_name='knowledge_b_mention_7fecb7_idx',
            old_name='knowledge_ba_mention__6a1f3c_idx',
        ),
    ]
