# Generated by Django 5.2.2 on 2026-06-27 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_subscription_billing_notification_fields'),
        ('knowledge_base', '0006_rename_knowledge_ba_target__7f1c2e_idx_knowledge_b_target__cf07b0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Owning workspace/team. Null means a global article visible to every team (used for platform-seeded baseline content) rather than per-tenant private content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_base_articles', to='base.team'),
        ),
    ]
