# Generated by Django 5.2.2 on 2026-07-08 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0031_blogpost'),
        ('tickets', '0016_alter_resolutiontemplate_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_workflows', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='base.team')),
                ('ticket', models.ForeignKey(blank=True, help_text='Null for a standalone workflow (started with no ticket).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assignee_team', models.CharField(blank=True, help_text="Descriptive label only in v1 (e.g. 'IT Support') -- not a queryable FK, so it doesn't drive notification routing yet.", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger_category', models.CharField(blank=True, help_text='Matches Ticket.category to auto-start this template on ticket creation. Blank means this template is only ever started manually (standalone).', max_length=30)),
                ('steps', models.JSONField(default=list, help_text='[{"title": "...", "description": "...", "assignee_team": "IT Support"}, ...] in order -- a flat list is enough for v1\'s strictly-sequential, no-branching shape.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, help_text='Null means a global template available to every team (platform-seeded baseline), same convention as KnowledgeBaseArticle.team.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='base.team')),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='workflows.workflowtemplate'),
        ),
    ]
