# Generated by Django 5.2.2 on 2026-07-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='auto_assign',
            field=models.CharField(blank=True, choices=[('', 'None'), ('started_by', 'Whoever started the workflow'), ('ticket_reporter', "The linked ticket's reporter")], default='', help_text='Copied from the template at creation time. If set, claimed_by is resolved automatically when this step becomes active, skipping the manual Claim click.', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='auto_complete',
            field=models.BooleanField(default=False, help_text='Copied from the template at creation time. If set, this step is marked done the instant it becomes active -- no human interaction (e.g. a pure log/notify checkpoint). Not an external action -- just workflow bookkeeping.'),
        ),
    ]
