# Generated by Django 5.2.2 on 2026-07-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowstep_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtemplate',
            name='steps',
            field=models.JSONField(default=list, help_text='[{"title": "...", "description": "...", "assignee_team": "IT Support", "due_days": 2}, ...] in order -- a flat list is enough for v1\'s strictly-sequential, no-branching shape. Optional due_days (default 2) sets step due_at when the step becomes active.'),
        ),
    ]
