# Generated by Django 5.2.2 on 2026-07-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_workflowstep_assignee_role_workflow_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='assignee_team',
            field=models.CharField(blank=True, help_text="Display label for the assignee group (e.g. 'IT Support').", max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='step_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('approval', 'Approval'), ('auto_check', 'Auto check')], default='manual', help_text='Copied from template at creation. Approval steps use an Approve action in UI.', max_length=20),
        ),
    ]
