# Generated by Django 5.2.2 on 2026-07-09 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_jira_escalate_sync'),
        ('workflows', '0008_step_assistant_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='child_ticket',
            field=models.ForeignKey(blank=True, help_text='Child ticket spawned when this step became active (P3-4).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_from_workflow_steps', to='tickets.ticket'),
        ),
    ]
