# Generated by Django 5.2.2 on 2026-07-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_cross_ticket_workflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='auto_assign',
            field=models.CharField(blank=True, choices=[('', 'None'), ('started_by', 'Whoever started the workflow'), ('ticket_reporter', "The linked ticket's reporter")], help_text='Copied from the template at creation time. If set, claimed_by is resolved automatically when this step becomes active, skipping the manual Claim click.', max_length=20),
        ),
    ]
