# Generated by Django 5.2.2 on 2026-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_alter_workflowstep_auto_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='step_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('approval', 'Approval'), ('auto_check', 'Auto check'), ('auto_action', 'Auto action (staff-confirmed)')], default='manual', help_text='Copied from template at creation. Approval steps use an Approve action in UI. Auto action steps propose a directory write (e.g. deactivate user) that a staff member must explicitly confirm -- never runs automatically.', max_length=20),
        ),
    ]
