# Generated by Django 5.2.2 on 2026-04-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_slacktoken_team_scope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='slacktoken',
            new_name='integration_resolve_e7a986_idx',
            old_name='integslack_team_active_idx',
        ),
    ]
