# Generated by Django 5.2.2 on 2026-06-30 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_teams_integration'),
        ('integrations', '0003_rename_integslack_team_active_idx_integration_resolve_e7a986_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='AAD tenant id', max_length=64)),
                ('teams_team_id', models.CharField(blank=True, db_index=True, help_text='Teams team (group) id; set once the bot is added to a team', max_length=128, null=True)),
                ('conversation_id', models.CharField(blank=True, default='', help_text='Default channel conversation id, used for escalation-channel posts', max_length=256)),
                ('service_url', models.URLField(blank=True, default='', help_text='serviceUrl to use for outbound Bot Framework calls to this tenant/team', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_app_installs', to=settings.AUTH_USER_MODEL)),
                ('resolvemeq_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_installations', to='base.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamsLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_by_installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.teamsinstallation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resolvemeq_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_link_codes', to='base.team')),
            ],
        ),
        migrations.AddIndex(
            model_name='teamsinstallation',
            index=models.Index(fields=['resolvemeq_team', 'is_active'], name='integration_resolve_06fec8_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamsinstallation',
            constraint=models.UniqueConstraint(condition=models.Q(('teams_team_id__isnull', False)), fields=('tenant_id', 'teams_team_id'), name='integrations_teamsinstallation_unique_tenant_team'),
        ),
        migrations.AddIndex(
            model_name='teamslinkcode',
            index=models.Index(fields=['resolvemeq_team', 'consumed_at'], name='integration_resolve_c0aea7_idx'),
        ),
    ]
