# Generated by Django 5.2.2 on 2026-07-09 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_profile_ops_role'),
        ('integrations', '0004_teams_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('url', models.URLField(max_length=512)),
                ('secret', models.CharField(max_length=128)),
                ('events', models.JSONField(blank=True, default=list, help_text='Empty list = all events; else subset of ticket.* / workflow.* events.')),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('circuit_open_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_endpoints_created', to=settings.AUTH_USER_MODEL)),
                ('resolvemeq_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='base.team')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.UUIDField(db_index=True, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('team_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('url', models.URLField(max_length=512)),
                ('secret', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['resolvemeq_team', 'is_active'], name='integration_resolve_ce5fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='integration_endpoin_d3e009_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['team_id', 'created_at'], name='integration_team_id_57678a_idx'),
        ),
    ]
