# Generated by Django 5.2.2 on 2026-07-09 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_profile_ops_role'),
        ('integrations', '0005_webhook_endpoints'),
        ('workflows', '0007_alter_workflowstep_assignee_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.CharField(db_index=True, max_length=32)),
                ('check_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('error', 'Error'), ('skipped', 'Skipped')], max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_check_logs', to='base.team')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_check_logs', to='workflows.workflow')),
                ('workflow_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_check_logs', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['-ran_at'],
                'indexes': [models.Index(fields=['workflow_step', 'ran_at'], name='integration_workflo_ae65ee_idx'), models.Index(fields=['team', 'connector', 'ran_at'], name='integration_team_id_d19e3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OktaInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okta_domain', models.CharField(help_text='Okta org subdomain, e.g. dev-12345678', max_length=128)),
                ('issuer_url', models.URLField(help_text='OAuth issuer, typically https://{domain}.okta.com/oauth2/default', max_length=512)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.CharField(blank=True, default='', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('circuit_open_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='okta_app_installs', to=settings.AUTH_USER_MODEL)),
                ('resolvemeq_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okta_installations', to='base.team')),
            ],
            options={
                'indexes': [models.Index(fields=['resolvemeq_team', 'is_active'], name='integration_resolve_0f64f5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('resolvemeq_team',), name='integrations_okta_one_active_per_team')],
            },
        ),
    ]
