# Generated by Django 5.2.2 on 2026-07-09 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_profile_ops_role'),
        ('integrations', '0006_okta_connector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleWorkspaceInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(blank=True, default='', max_length=254)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.CharField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('circuit_open_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_workspace_installs', to=settings.AUTH_USER_MODEL)),
                ('resolvemeq_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_workspace_installations', to='base.team')),
            ],
            options={
                'indexes': [models.Index(fields=['resolvemeq_team', 'is_active'], name='integration_resolve_8ce3fb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('resolvemeq_team',), name='integrations_google_one_active_per_team')],
            },
        ),
        migrations.CreateModel(
            name='Microsoft365Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, default='', max_length=64)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.CharField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('circuit_open_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microsoft365_installs', to=settings.AUTH_USER_MODEL)),
                ('resolvemeq_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft365_installations', to='base.team')),
            ],
            options={
                'indexes': [models.Index(fields=['resolvemeq_team', 'is_active'], name='integration_resolve_f27e5c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('resolvemeq_team',), name='integrations_m365_one_active_per_team')],
            },
        ),
    ]
