# Generated by Django 5.2.2 on 2026-07-09 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_profile_ops_role'),
        ('integrations', '0007_google_m365_connectors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(help_text='https://your-org.atlassian.net', max_length=256)),
                ('user_email', models.CharField(help_text='Atlassian account email for API token auth', max_length=254)),
                ('api_token', models.TextField(help_text='Jira Cloud API token')),
                ('project_key', models.CharField(default='SUP', max_length=32)),
                ('issue_type', models.CharField(default='Task', max_length=64)),
                ('sync_on_escalate', models.BooleanField(default=True)),
                ('sync_on_resolve', models.BooleanField(default=True)),
                ('resolve_transition', models.CharField(default='Done', help_text='Jira transition name when ticket is resolved', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('circuit_open_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_installs', to=settings.AUTH_USER_MODEL)),
                ('resolvemeq_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_installations', to='base.team')),
            ],
            options={
                'indexes': [models.Index(fields=['resolvemeq_team', 'is_active'], name='integration_resolve_875e2d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('resolvemeq_team',), name='integrations_jira_one_active_per_team')],
            },
        ),
    ]
