# Generated by Django 5.2.2 on 2026-07-14 22:01

import base.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_jira_escalate_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleworkspaceinstallation',
            name='access_token',
            field=base.encrypted_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='googleworkspaceinstallation',
            name='refresh_token',
            field=base.encrypted_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jirainstallation',
            name='api_token',
            field=base.encrypted_fields.EncryptedTextField(help_text='Jira Cloud API token'),
        ),
        migrations.AlterField(
            model_name='microsoft365installation',
            name='access_token',
            field=base.encrypted_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='microsoft365installation',
            name='refresh_token',
            field=base.encrypted_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='oktainstallation',
            name='access_token',
            field=base.encrypted_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='oktainstallation',
            name='refresh_token',
            field=base.encrypted_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='slacktoken',
            name='access_token',
            field=base.encrypted_fields.EncryptedTextField(help_text='Slack bot token (xoxb-...)'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='secret',
            field=base.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret',
            field=base.encrypted_fields.EncryptedTextField(),
        ),
    ]
