# Generated by Django 5.2.2 on 2026-07-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_alter_googleworkspaceinstallation_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slacktoken',
            name='escalation_channel_id',
            field=models.CharField(blank=True, default='', help_text='Slack channel ID (e.g. C01234ABCD) escalations for this team post to. Falls back to the deployment-wide SLACK_ESCALATION_CHANNEL setting when blank.', max_length=32),
        ),
    ]
