# Generated by Django 5.2.2 on 2026-07-15 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_rename_base_teamwo_team_id_6f0a8a_idx_base_teamwo_team_id_4989a6_idx'),
        ('integrations', '0010_slacktoken_escalation_channel_id'),
        ('workflows', '0011_alter_workflowstep_step_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.CharField(db_index=True, max_length=32)),
                ('action_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('error', 'Error'), ('skipped', 'Skipped')], max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_actions_executed', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_action_logs', to='base.team')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_action_logs', to='workflows.workflow')),
                ('workflow_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_action_logs', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['-ran_at'],
                'indexes': [models.Index(fields=['workflow_step', 'ran_at'], name='integration_workflo_2f05a1_idx'), models.Index(fields=['team', 'connector', 'ran_at'], name='integration_team_id_55c3a8_idx')],
            },
        ),
    ]
