# Generated by Django 5.2.2 on 2026-07-09 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0033_msp_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('ticket.created', 'Ticket created'), ('ticket.escalated', 'Ticket escalated'), ('ticket.resolved', 'Ticket resolved'), ('workflow.step.completed', 'Workflow step completed'), ('rule.executed', 'Rule executed'), ('rule.created', 'Rule created'), ('rule.updated', 'Rule updated'), ('rule.deleted', 'Rule deleted'), ('msp.enabled', 'MSP mode enabled'), ('msp.client_created', 'MSP client created'), ('audit.exported', 'Audit log exported')], max_length=64)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=128)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_audit_events', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_audit_events', to='base.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'created_at'], name='monitoring__team_id_4e89c2_idx'), models.Index(fields=['event_type', 'created_at'], name='monitoring__event_t_99fc0d_idx')],
            },
        ),
    ]
