# Generated by Django 5.2.2 on 2026-02-26 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the team', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the team', max_length=200, unique=True, verbose_name='team name')),
                ('description', models.TextField(blank=True, help_text="Description of the team's purpose and responsibilities", verbose_name='description')),
                ('department', models.CharField(blank=True, help_text='Department the team belongs to', max_length=100, verbose_name='department')),
                ('location', models.CharField(blank=True, help_text='Physical or virtual location of the team', max_length=200, verbose_name='location')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this team is currently active', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the team was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the team was last updated', verbose_name='updated at')),
                ('lead', models.ForeignKey(blank=True, help_text='User who leads this team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='team lead')),
                ('members', models.ManyToManyField(blank=True, help_text='Users who are members of this team', related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='team members')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='base_team_name_7bc2c1_idx'), models.Index(fields=['department'], name='base_team_departm_15fbb4_idx'), models.Index(fields=['is_active'], name='base_team_is_acti_20a1b6_idx')],
            },
        ),
    ]
