# Generated by Django 5.2.2 on 2026-02-26 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications', verbose_name='email notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications', verbose_name='push notifications')),
                ('ticket_updates', models.BooleanField(default=True, help_text='Notify on ticket updates', verbose_name='ticket updates')),
                ('system_alerts', models.BooleanField(default=True, help_text='Receive system alerts', verbose_name='system alerts')),
                ('daily_digest', models.BooleanField(default=False, help_text='Receive daily digest emails', verbose_name='daily digest')),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone", max_length=50, verbose_name='timezone')),
                ('language', models.CharField(default='en', help_text='Preferred language', max_length=10, verbose_name='language')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', help_text='UI theme preference', max_length=20, verbose_name='theme')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When preferences were created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When preferences were last updated', verbose_name='updated at')),
                ('user', models.OneToOneField(help_text='User associated with these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
