# Generated by Django 5.2.2 on 2026-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userpreferences_active_team'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'email'), name='unique_pending_invitation_per_team_email'),
        ),
    ]
