# Generated by Django 5.2.2 on 2026-03-04 00:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_in_app_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('company_size', models.CharField(choices=[('1-50', '1-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501+', '501+ employees')], max_length=10, verbose_name='company size')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False, verbose_name='contacted')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Contact request',
                'verbose_name_plural': 'Contact requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
            ],
            options={
                'verbose_name': 'Newsletter subscription',
                'verbose_name_plural': 'Newsletter subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
