# Generated by Django 5.2.2 on 2026-03-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_invoice_gateway_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingwebhookdelivery',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
