# Generated by Django 5.2.2 on 2026-05-15 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_subscription_expired_notified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionGrantLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status_after', models.CharField(blank=True, default='', max_length=20)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_gateway', models.BooleanField(default=False)),
                ('months_applied', models.PositiveSmallIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_grants_made', to=settings.AUTH_USER_MODEL, verbose_name='granted by')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_logs', to='base.plan')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_grant_logs', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_logs', to='base.subscription')),
            ],
            options={
                'verbose_name': 'Subscription grant log',
                'verbose_name_plural': 'Subscription grant logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
