# Generated by Django 5.2.2 on 2026-06-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_subscription_billing_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_agent',
            field=models.BooleanField(default=False, help_text="ResolveMeQ support staff who can claim/reply to escalated tickets across any customer's team -- independent of is_staff (Django admin access).", verbose_name='platform support agent'),
        ),
    ]
