# Generated by Django 5.2.2 on 2026-06-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_user_is_platform_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teams_aad_object_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Teams/AAD object id for proactive messaging; optional', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='teams_conversation_id',
            field=models.CharField(blank=True, default='', help_text='Cached 1:1 conversation id for this user, avoids re-creating it on every notify', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='teams_tenant_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='AAD tenant id this user is linked to; optional', max_length=64),
        ),
    ]
