# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_supportcontactsubmission_ticket_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=220, unique=True, verbose_name="slug")),
                ("title", models.CharField(max_length=300, verbose_name="title")),
                ("excerpt", models.TextField(max_length=2000, verbose_name="excerpt")),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown-ish body with ## and ### headings.",
                        verbose_name="body",
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="category")),
                ("read_time_minutes", models.PositiveSmallIntegerField(default=10, verbose_name="read time (minutes)")),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional public https URL for hero/OG image; leave empty when none.",
                        max_length=500,
                        null=True,
                        verbose_name="hero image URL",
                    ),
                ),
                ("author_name", models.CharField(blank=True, default="", max_length=120, verbose_name="author name")),
                ("published_at", models.DateField(verbose_name="published date")),
                ("is_published", models.BooleanField(default=True, verbose_name="published")),
                ("is_ai_generated", models.BooleanField(default=False, verbose_name="AI generated")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blog post",
                "verbose_name_plural": "Blog posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
