# Generated by Django 5.2.2 on 2026-07-09 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_profile_ops_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='msp_parent',
            field=models.ForeignKey(blank=True, help_text='MSP hub team when team_kind is msp_client.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msp_clients', to='base.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_kind',
            field=models.CharField(choices=[('workspace', 'Workspace'), ('msp', 'MSP hub'), ('msp_client', 'MSP client')], default='workspace', help_text='MSP hub manages linked client workspaces (P3-5).', max_length=16),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_kind', 'msp_parent'], name='base_team_team_ki_d1fabb_idx'),
        ),
    ]
