# Generated by Django 5.2 on 2026-07-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0033_msp_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamWorkspaceAdmin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_admins_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_admin_grants",
                        to="base.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_admin_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace admin",
                "verbose_name_plural": "workspace admins",
            },
        ),
        migrations.AddIndex(
            model_name="teamworkspaceadmin",
            index=models.Index(fields=["team", "user"], name="base_teamwo_team_id_6f0a8a_idx"),
        ),
        migrations.AddConstraint(
            model_name="teamworkspaceadmin",
            constraint=models.UniqueConstraint(fields=("team", "user"), name="uniq_team_workspace_admin"),
        ),
    ]
