# Generated by Django 5.2.2 on 2026-07-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_invoice_gateway_payment_id_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teamworkspaceadmin',
            new_name='base_teamwo_team_id_4989a6_idx',
            old_name='base_teamwo_team_id_6f0a8a_idx',
        ),
    ]
