# Generated by Django 5.2.2 on 2026-07-08 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('base', '0032_profile_ops_role'),
        ('tickets', '0018_alter_resolutiontemplate_category_and_more'),
        ('workflows', '0007_alter_workflowstep_assignee_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('schedule.cron', 'schedule.cron'), ('ticket.created', 'ticket.created'), ('ticket.escalated', 'ticket.escalated'), ('ticket.resolved', 'ticket.resolved'), ('workflow.step.completed', 'workflow.step.completed')], max_length=50)),
                ('conditions', models.JSONField(blank=True, default=list, help_text='AND list, e.g. [{"field": "category", "op": "equals", "value": "onboarding"}]')),
                ('actions', models.JSONField(default=list, help_text='e.g. [{"type": "start_workflow", "template_trigger_category": "onboarding"}]')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower numbers run first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, help_text='Null = global rule (platform-seeded defaults).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='base.team')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('dry_run', 'Dry run')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('actions_planned', models.JSONField(blank=True, default=list)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='automation.rule')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_execution_logs', to='base.team')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_execution_logs', to='tickets.ticket')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_execution_logs', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
