# Generated by Django 5.2.2 on 2026-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_rule_ruleexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='cron_expression',
            field=models.CharField(blank=True, help_text="5-field cron expression, UTC (e.g. '0 9 * * 1' = every Monday 09:00 UTC). Required when trigger is schedule.cron.", max_length=100),
        ),
        migrations.AddField(
            model_name='rule',
            name='cron_last_fired_at',
            field=models.DateTimeField(blank=True, help_text='Set by the cron dispatcher; prevents firing twice for the same due minute.', null=True),
        ),
    ]
