# Generated by Django 5.2.2 on 2026-02-27 10:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(help_text='AUTO_RESOLVE, ESCALATE, etc.', max_length=50)),
                ('action_params', models.JSONField(default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.CharField(default='autonomous_agent', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('agent_reasoning', models.TextField(blank=True)),
                ('rollback_possible', models.BooleanField(default=False)),
                ('rollback_steps', models.JSONField(blank=True, null=True)),
                ('rolled_back', models.BooleanField(default=False)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_reason', models.TextField(blank=True)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollbacks_performed', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_history', to='tickets.ticket')),
            ],
            options={
                'db_table': 'action_history',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['ticket', 'action_type'], name='action_hist_ticket__3e3d6b_idx'), models.Index(fields=['executed_at'], name='action_hist_execute_b4ed36_idx'), models.Index(fields=['rolled_back'], name='action_hist_rolled__1bb1ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autonomous_action', models.CharField(help_text='Type of autonomous action taken', max_length=50)),
                ('resolution_confirmed', models.BooleanField(blank=True, help_text='User confirmed resolution worked (True) or failed (False)', null=True)),
                ('user_feedback_text', models.TextField(blank=True)),
                ('satisfaction_score', models.IntegerField(blank=True, help_text='User satisfaction rating 1-5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('followup_sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('reopened', models.BooleanField(default=False)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_tracking', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_resolution',
                'indexes': [models.Index(fields=['autonomous_action', 'resolution_confirmed'], name='ticket_reso_autonom_37aae3_idx'), models.Index(fields=['satisfaction_score'], name='ticket_reso_satisfa_0eb740_idx')],
            },
        ),
    ]
