# Generated by Django 5.2.2 on 2026-03-04 02:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_actionhistory_ticketresolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='Ticket category this applies to', max_length=50)),
                ('label', models.CharField(help_text='Button text shown to user', max_length=100)),
                ('message_text', models.TextField(help_text='Message sent when clicked')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shown first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-priority', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of conversation')),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_applied', models.BooleanField(default=False, help_text='Did user apply suggested solution?')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI Assistant'), ('system', 'System')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('steps', 'Step-by-step guide'), ('question', 'Question with choices'), ('solution', 'Proposed solution'), ('file_request', 'File upload request'), ('similar_tickets', 'Similar tickets'), ('kb_article', 'Knowledge base article')], default='text', max_length=20)),
                ('text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data (steps, choices, attachments, etc.)')),
                ('confidence', models.FloatField(blank=True, help_text='AI confidence score (0.0-1.0)', null=True)),
                ('agent_response_data', models.JSONField(blank=True, help_text='Full agent response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_helpful', models.BooleanField(blank=True, help_text='User feedback on AI message', null=True)),
                ('feedback_comment', models.TextField(blank=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['ticket', '-updated_at'], name='tickets_con_ticket__9b529e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='tickets_con_user_id_15d9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='tickets_cha_convers_fd6a24_idx'),
        ),
    ]
