# Generated by Django 5.2.2 on 2026-03-04 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_chatconversation_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'Email Sync - Outlook')", max_length=200)),
                ('description', models.TextField(help_text='Description of when to use this template')),
                ('category', models.CharField(choices=[('wifi', 'Wi-Fi'), ('laptop', 'Laptop'), ('vpn', 'VPN'), ('printer', 'Printer'), ('email', 'Email'), ('software', 'Software'), ('hardware', 'Hardware'), ('network', 'Network'), ('account', 'Account'), ('access', 'Access'), ('phone', 'Phone'), ('server', 'Server'), ('security', 'Security'), ('cloud', 'Cloud'), ('storage', 'Storage'), ('other', 'Other')], help_text='Primary category this template applies to', max_length=30)),
                ('issue_types', models.JSONField(default=list, help_text='List of issue types this template can resolve')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for filtering')),
                ('steps', models.JSONField(help_text="Array of resolution steps: [{step: 1, action: '...', description: '...'}]")),
                ('estimated_time', models.CharField(default='10 minutes', help_text="Estimated time to complete (e.g., '5-10 minutes')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this template has been applied')),
                ('success_count', models.IntegerField(default=0, help_text='Number of successful resolutions using this template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and can be used')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Whether this template was generated by AI')),
                ('custom_params', models.JSONField(blank=True, default=dict, help_text='Custom parameters that can be filled when applying template')),
                ('created_by', models.ForeignKey(help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resolution_templates',
                'ordering': ['-use_count', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='resolution__categor_95b7bd_idx'), models.Index(fields=['use_count'], name='resolution__use_cou_2c6d1c_idx'), models.Index(fields=['created_at'], name='resolution__created_f98901_idx')],
            },
        ),
    ]
