# Generated by Django 5.2.2 on 2026-03-22 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_supportcontactsubmission'),
        ('tickets', '0005_ticket_team'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_ticket_team_status_idx',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='team',
            field=models.ForeignKey(blank=True, help_text="Workspace/team; set from creator's active team when applicable.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='base.team'),
        ),
    ]
