# Generated by Django 5.2.2 on 2026-03-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_conversation_initial_solution_feedback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentconfidencelog',
            new_name='tickets_age_ticket__6d35d1_idx',
            old_name='tickets_age_ticket_i_7b8c9d_idx',
        ),
        migrations.RenameIndex(
            model_name='agentconfidencelog',
            new_name='tickets_age_source_fec861_idx',
            old_name='tickets_age_source_i_8c9d0e_idx',
        ),
    ]
