# Generated by Django 5.2.2 on 2026-06-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_conversation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When a support agent first picked up this escalated ticket. Set once; sticky across status changes.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_priority',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Priority derived at escalation time; drives SLA and queue ordering.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, help_text='Computed deadline (escalated_at + SLA hours for priority). Not paused/recomputed.', null=True),
        ),
    ]
