# Generated by Django 5.2.2 on 2026-06-28 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_escalation_priority_claim_sla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(blank=True, help_text="Set only for sender_type='agent' -- which teammate wrote this reply.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI Assistant'), ('system', 'System'), ('agent', 'Support Agent')], max_length=10),
        ),
    ]
