# Generated by Django 5.2.2 on 2026-06-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticket_slack_thread_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='teams_reply_to_id',
            field=models.CharField(blank=True, default='', help_text="Root Teams activity id for this ticket's reporter conversation, for threaded replies.", max_length=128),
        ),
    ]
