# Generated by Django 5.2.2 on 2026-07-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_teams_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reported_platform',
            field=models.CharField(blank=True, choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], help_text="Reporter's OS if known from the browser (navigator.userAgentData/platform); lets the AI generate an accurate remediation_script instead of asking or guessing.", max_length=10, null=True),
        ),
    ]
