# Generated by Django 5.2.2 on 2026-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_resolutiontemplate_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutiontemplate',
            name='category',
            field=models.CharField(choices=[('wifi', 'Wi-Fi'), ('laptop', 'Laptop'), ('vpn', 'VPN'), ('printer', 'Printer'), ('email', 'Email'), ('software', 'Software'), ('hardware', 'Hardware'), ('network', 'Network'), ('account', 'Account'), ('access', 'Access'), ('phone', 'Phone'), ('server', 'Server'), ('security', 'Security'), ('cloud', 'Cloud'), ('storage', 'Storage'), ('provisioning', 'Provisioning'), ('onboarding', 'Onboarding'), ('offboarding', 'Offboarding'), ('other', 'Other')], help_text='Primary category this template applies to', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('wifi', 'Wi-Fi'), ('laptop', 'Laptop'), ('vpn', 'VPN'), ('printer', 'Printer'), ('email', 'Email'), ('software', 'Software'), ('hardware', 'Hardware'), ('network', 'Network'), ('account', 'Account'), ('access', 'Access'), ('phone', 'Phone'), ('server', 'Server'), ('security', 'Security'), ('cloud', 'Cloud'), ('storage', 'Storage'), ('provisioning', 'Provisioning'), ('onboarding', 'Onboarding'), ('offboarding', 'Offboarding'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
