# Generated by Django 5.2.2 on 2026-07-09 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_resolutiontemplate_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(db_index=True, max_length=32)),
                ('external_id', models.CharField(help_text='External key, e.g. SUP-123', max_length=128)),
                ('external_url', models.URLField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_references', to='tickets.ticket')),
            ],
            options={
                'indexes': [models.Index(fields=['system', 'external_id'], name='tickets_ext_system_710033_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'system'), name='tickets_externalreference_unique_ticket_system')],
            },
        ),
    ]
