# Generated by Django 5.2.2 on 2026-07-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_jira_escalate_sync'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', 'status'], name='tickets_tic_team_id_3fd380_idx'),
        ),
    ]
