# Generated by Django 5.2.2 on 2026-07-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_ticket_tickets_tic_team_id_3fd380_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_clarification', 'Pending Clarification'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], max_length=50),
        ),
    ]
