# Generated by Django 5.2.2 on 2026-07-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Set automatically at creation when this looks like the same issue as another open ticket from the same reporter (see tickets/services.py). Informational only -- never blocks or changes ticket behavior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='tickets.ticket'),
        ),
    ]
