# Generated by Django 5.2.2 on 2026-07-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_rename_base_teamwo_team_id_6f0a8a_idx_base_teamwo_team_id_4989a6_idx'),
        ('tickets', '0022_ticket_duplicate_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='base.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='incident',
            field=models.ForeignKey(blank=True, help_text="Set automatically when this ticket clusters with several other reporters' similar tickets on the same team (see tickets/incident_clustering.py). Informational only.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.incident'),
        ),
    ]
